name: Projects macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and install
      run: |
        git config --global url."https://github.com/".insteadOf git@github.com:
        git config --global url."https://".insteadOf git://
        cmake -G Xcode -Bbuild_macos -H.
        xcodebuild -project ./build_macos/Projects.xcodeproj -configuration Release

    - name: Run tests
      run: |
        cd build_macos/Release
        ./ProjectsTests
